name: super_cupertino_navigation_bar
description: This package offers a collapsible app bar along with an attractive search bar animation, enhancing the visual appeal of your Flutter app with an iOS-inspired design. This package is versatile, allowing complete customization, and it seamlessly works on both iOS and Android platforms.
version: 2.1.0
homepage: https://github.com/kspo/super_cupertino_navigation_bar.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  snap_scroll_physics: ^0.0.1+3
  nested_scroll_view_plus: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0