name: super_cupertino_navigation_bar
description: This is most desired plugin of Cupertino Navigation Bar With Search Field and Avatar
version: 1.1.0
homepage: https://github.com/kspo/super_cupertino_navigation_bar.git

environment:
  sdk: '>=3.1.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0